#!/usr/bin/perl
use strict;
use warnings;
use Getopt::Long;

my ( $infile, $outfile );
GetOptions(
	'infile=s'  => \$infile,
	'outfile=s' => \$outfile,
);

open my $in,  '<', $infile  or die $!;
open my $out, '>', $outfile or die $!;

while(<$in>) {
	print $out "parallel: ", $_;
}