#!/usr/bin/perl
use strict;
use warnings;
use Getopt::Long;

my ( $infile, $outfiles );
GetOptions(
	'input=s'  => \$infile,
	'output=s' => \$outfiles,
);

my @outfiles = split /\s+/, $outfiles;

open my $in, '<', $infile or die $!;
while(<$in>) {
	chomp;
	my ( $prefix, $index ) = split /\t/, $_;	
	open my $out, '>', $outfiles[$index-1] or die $!;
	print $out $_;
	close $out;
}